project_name: terraform-provider-virtfusion

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-virtfusion
    main: .
    binary: "{{ .ProjectName }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }}"

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"

signs:
  - cmd: gpg
    args:
      [
        "--batch",
        "--yes",
        "--pinentry-mode", "loopback",
        "--passphrase", "",
        "--armor",
        "--output", "${signature}",
        "--detach-sign", "${artifact}"
      ]
    artifacts: checksum
    signature: "${artifact}.sig"
    output: true




changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
