project_name: terraform-provider-virtfusion

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-virtfusion
    main: .
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version={{.Version}}"

archives:
  - id: release
    format: zip
    builds:
      - terraform-provider-virtfusion
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: amd64
      arm64: arm64
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS"

signs:
  - artifacts: checksum
    args: ["--batch", "--yes", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

release:
  draft: false
  prerelease: false
  mode: replace
