version: 2

project_name: terraform-provider-virtfusion

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-virtfusion
    main: .
    binary: terraform-provider-virtfusion
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: zip
    files:
      - none*

checksum:
  name_template: "checksums.txt"

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--yes"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase"
      - "${GPG_PASSPHRASE}"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

changelog:
  use: git
