version: 2

project_name: terraform-provider-virtfusion

before:
  hooks:
    - go mod tidy

builds:
  - id: virtfusion
    main: .
    binary: terraform-provider-virtfusion
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: archive
    builds:
      - virtfusion
    format: zip
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS"

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--yes"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase-file"
      - ".gpg_passphrase"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
