project_name: terraform-provider-virtfusion

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-virtfusion
    main: .
    # Binary inside the archive should include the leading "v"
    binary: terraform-provider-virtfusion_v{{ .Version }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: zip
    # Archive filename must NOT include the leading "v"
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  # Checksums filename must NOT include the leading "v" (already correct)
  name_template: "terraform-provider-virtfusion_{{ .Version }}_SHA256SUMS"

signs:
  - cmd: gpg
    args:
      [
        "--batch",
        "--yes",
        "--local-user", "485EB74C6A039FC89BE5359DE3A58B345981499F",
        "--armor",
        "--output", "${signature}",
        "--detach-sign", "${artifact}"
      ]
    artifacts: checksum
    signature: "${artifact}.sig"
    output: true

release:
  github:
    owner: snowsidejon
    name: terraform-provider-virtfusion
