name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GPG_FINGERPRINT: 8BF2DA5FF04681174B1814C59213DFF34C99F136
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

